"""
Response Signer — HMAC-SHA256 attestation for proxy responses.

Signs each response to prove it passed through this proxy instance
and was not modified after leaving the proxy. This is ATTESTATION,
not provenance — it proves "the proxy saw and forwarded this content",
NOT "this content was generated by a specific LLM model".

Threat model this addresses:
  ✅ Proxy → Client tampering (MITM modifying responses after the proxy)
  ✅ Response replay attacks — ONLY when the verifier enforces freshness:
     the timestamp is signed, but a signed timestamp proves nothing on its own
     (the presenter supplies it). `verify(..., max_age_seconds=N)` rejects
     timestamps older than N seconds (and future-dated ones), which is what
     actually bounds replay. Without max_age_seconds, a captured tuple verifies
     forever.
  ✅ Audit trail integrity (signature ties response to specific request_id)
  ❌ LLM → Proxy tampering (no LLM provider signs responses today)
  ❌ Model identity proof (only the provider could attest to that)

The LLM → Proxy gap is an industry-wide limitation, not specific to this
implementation. When providers start signing responses, we can chain
their signature into ours.

Config:
  security:
    response_signing:
      enabled: true
      # Secret: from env var LLM_PROXY_SIGNING_KEY, or config (env preferred)

Headers injected:
  X-LLMProxy-Signature: HMAC-SHA256 hex digest
  X-LLMProxy-Signed-At: ISO 8601 timestamp
  X-LLMProxy-Signed-Fields: comma-separated list of signed fields
"""

import calendar
import hmac
import hashlib
import time
import logging

logger = logging.getLogger("llmproxy.response_signer")


class ResponseSigner:
    """Signs proxy responses with HMAC-SHA256 for tamper detection (proxy→client)."""

    def __init__(self, secret: str = ""):
        if secret:
            self._key = secret.encode("utf-8")
            self.enabled = True
        else:
            self._key = b""
            self.enabled = False
            logger.info("Response signing disabled (no signing key configured)")

    def sign_response(
        self,
        response_body: bytes,
        model: str = "",
        provider: str = "",
        request_id: str = "",
    ) -> dict[str, str]:
        """Compute HMAC-SHA256 attestation over response + metadata.

        This proves the response was not tampered with after leaving the proxy.
        It does NOT prove the response was generated by the claimed model
        (that would require provider-side signing, which no provider offers).

        Returns dict of headers to inject into the response.
        Returns empty dict if signing is disabled.
        """
        if not self.enabled:
            return {}

        timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        # Build the message to sign: deterministic concatenation
        # Using | as separator (not present in base64/hex)
        message = f"{model}|{provider}|{timestamp}|{request_id}|".encode("utf-8")
        message += response_body

        sig = hmac.new(self._key, message, hashlib.sha256).hexdigest()

        return {
            "X-LLMProxy-Signature": sig,
            "X-LLMProxy-Signed-At": timestamp,
            "X-LLMProxy-Signed-Fields": "model,provider,timestamp,request_id,body",
        }

    @staticmethod
    def verify(
        secret: str,
        response_body: bytes,
        model: str,
        provider: str,
        timestamp: str,
        request_id: str,
        expected_signature: str,
        max_age_seconds: "int | None" = None,
        clock_skew_seconds: int = 60,
    ) -> bool:
        """Verify a response signature (client-side or audit tool).

        Args:
            secret: Shared signing key
            response_body: Raw response bytes
            model, provider, timestamp, request_id: Signed metadata fields
            expected_signature: The X-LLMProxy-Signature header value
            max_age_seconds: If set, REJECT signatures whose signed timestamp is
                older than this many seconds, or dated more than
                `clock_skew_seconds` in the future. This is what actually
                prevents replay — the HMAC alone authenticates the timestamp but
                does not bound its age. Leave None only for offline audit tools
                that intentionally verify historical entries.
            clock_skew_seconds: Tolerance for a future-dated timestamp.

        Returns True if signature matches (and, when max_age_seconds is set, the
        timestamp is fresh); False otherwise.
        """
        message = f"{model}|{provider}|{timestamp}|{request_id}|".encode("utf-8")
        message += response_body

        computed = hmac.new(secret.encode("utf-8"), message, hashlib.sha256).hexdigest()
        if not hmac.compare_digest(computed, expected_signature):
            return False

        # Freshness gate — the signature is valid, but a valid signature over a
        # stale timestamp is exactly a replay. Enforce the window when asked.
        if max_age_seconds is not None:
            try:
                # timegm interprets the struct as UTC (the timestamp is emitted
                # via time.gmtime); mktime would wrongly treat it as local time.
                signed_epoch = calendar.timegm(time.strptime(timestamp, "%Y-%m-%dT%H:%M:%SZ"))
            except (ValueError, TypeError):
                return False  # unparseable timestamp on a freshness-checked verify
            now = time.time()
            age = now - signed_epoch
            if age > max_age_seconds or age < -clock_skew_seconds:
                return False
        return True
