#!/usr/bin/env bash
# scripts/bootstrap-remote.sh — recover a fresh or wiped remote box to the point
# where scripts/deploy.sh can run. Idempotent: it never overwrites an existing
# keys.env, config.yaml, or git checkout — it only creates what is missing.
#
# This exists because deploy.sh assumes the runtime state dir
# (REMOTE_STATE_DIR/{keys.env,config.yaml}) and the build checkout (REMOTE_DIR)
# already exist. When the box is new — or its /opt/llmproxy got wiped, which
# crash-loops the systemd unit on `docker run --env-file` — bootstrap rebuilds
# that floor in one command.
#
# What it does (each step skipped if already satisfied):
#   1. mkdir REMOTE_STATE_DIR
#   2. write keys.env with freshly generated internal secrets
#      (LLM_PROXY_API_KEYS / MASTER_KEY / IDENTITY_SECRET) + provider placeholders
#   3. copy local config.minimal.yaml → REMOTE_STATE_DIR/config.yaml
#   4. git clone REMOTE_REPO_URL → REMOTE_DIR
#   5. print the generated proxy key (for the Admin UI login)
#
# It does NOT touch the systemd unit or restart anything — run deploy.sh after,
# or `systemctl restart <unit>` to come up on the current image.
#
# Usage:
#   scripts/bootstrap-remote.sh                 # create whatever is missing
#   scripts/bootstrap-remote.sh --show-key      # also re-print an existing proxy key
#
# Env overrides (same names/defaults as deploy.sh):
#   REMOTE_HOST=100.76.251.33  REMOTE_USER=root
#   REMOTE_DIR=/opt/llmproxy-src   REMOTE_STATE_DIR=/opt/llmproxy
#   REMOTE_REPO_URL=https://github.com/fabriziosalmi/llmproxy.git
#   CONFIG_SRC=<local path>    (defaults to repo config.minimal.yaml)

set -euo pipefail

REMOTE_HOST="${REMOTE_HOST:-100.76.251.33}"
REMOTE_USER="${REMOTE_USER:-root}"
REMOTE_DIR="${REMOTE_DIR:-/opt/llmproxy-src}"
REMOTE_STATE_DIR="${REMOTE_STATE_DIR:-/opt/llmproxy}"
REMOTE_REPO_URL="${REMOTE_REPO_URL:-https://github.com/fabriziosalmi/llmproxy.git}"

SHOW_KEY=0
[ "${1:-}" = "--show-key" ] && SHOW_KEY=1

ROOT="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$ROOT" ] || { echo "✗ Not inside a git repo." >&2; exit 1; }
CONFIG_SRC="${CONFIG_SRC:-$ROOT/config.minimal.yaml}"
[ -f "$CONFIG_SRC" ] || { echo "✗ Config source not found: $CONFIG_SRC" >&2; exit 1; }

SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o BatchMode=yes -o ConnectTimeout=10)
ssh_exec() { ssh "${SSH_OPTS[@]}" "$REMOTE_USER@$REMOTE_HOST" "$@"; }

log()  { printf '\033[1;36m▸\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }

log "Bootstrapping ${REMOTE_USER}@${REMOTE_HOST}"
log "  state dir: ${REMOTE_STATE_DIR}   src dir: ${REMOTE_DIR}"

# 1+2: state dir + keys.env (generate secrets remotely so they never touch the
# local shell history/args). Idempotent: keys.env is only written if absent.
PROXY_KEY=$(ssh_exec env \
    REMOTE_STATE_DIR="$REMOTE_STATE_DIR" \
    SHOW_KEY="$SHOW_KEY" \
    bash -s <<'REMOTE_KEYS'
set -euo pipefail
mkdir -p "$REMOTE_STATE_DIR"
KF="$REMOTE_STATE_DIR/keys.env"
if [ -f "$KF" ]; then
    if [ "$SHOW_KEY" = "1" ]; then
        echo "SHOWN:$(grep '^LLM_PROXY_API_KEYS=' "$KF" | cut -d= -f2)"
    else
        echo "__EXISTS__"
    fi
    exit 0
fi
PK="sk-proxy-$(openssl rand -hex 16)"
umask 077
cat > "$KF" <<KENV
# llmproxy keys.env — generated by bootstrap-remote.sh.
# Internal secrets are freshly generated; fill in provider keys to enable routing.
LLM_PROXY_API_KEYS=${PK}
LLM_PROXY_MASTER_KEY=$(openssl rand -hex 32)
LLM_PROXY_IDENTITY_SECRET=$(openssl rand -hex 32)
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GOOGLE_API_KEY=
KENV
chmod 600 "$KF"
echo "CREATED:$PK"
REMOTE_KEYS
)

case "$PROXY_KEY" in
    __EXISTS__)
        ok "keys.env already present — left untouched (use --show-key to read the key)";;
    SHOWN:*)
        ok "keys.env already present — left untouched"
        printf '\033[1;33m  PROXY KEY (Admin UI login):\033[0m %s\n' "${PROXY_KEY#SHOWN:}";;
    CREATED:*)
        ok "keys.env created"
        printf '\033[1;33m  PROXY KEY (save it, use for Admin UI login):\033[0m %s\n' "${PROXY_KEY#CREATED:}";;
esac

# 3: config.yaml — only if absent.
if ssh_exec "[ -f '$REMOTE_STATE_DIR/config.yaml' ]"; then
    ok "config.yaml already present — left untouched"
else
    ssh_exec "cat > '$REMOTE_STATE_DIR/config.yaml' && chmod 644 '$REMOTE_STATE_DIR/config.yaml'" < "$CONFIG_SRC"
    ok "config.yaml written from $(basename "$CONFIG_SRC")"
fi

# 4: source checkout — clone only if not already a repo.
if ssh_exec "git -C '$REMOTE_DIR' rev-parse --git-dir >/dev/null 2>&1"; then
    ok "source checkout already present at ${REMOTE_DIR}"
else
    log "cloning ${REMOTE_REPO_URL} → ${REMOTE_DIR}"
    ssh_exec "rm -rf '$REMOTE_DIR' && git clone --quiet '$REMOTE_REPO_URL' '$REMOTE_DIR'"
    ok "source cloned"
fi

printf '\n'
ok "Bootstrap complete. Next:"
printf '   scripts/deploy.sh            # build + deploy latest main\n'
printf '   # or just bring up the current image:\n'
printf '   ssh %s@%s systemctl restart llmproxy\n' "$REMOTE_USER" "$REMOTE_HOST"
