{{- if and .Values.secrets.inline (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llmproxy.fullname" . }}-secrets
  labels:
    {{- include "llmproxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.inline }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
